application: kmadswebsite
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: django
  version: latest

handlers:
- url: /style
  static_dir: static/style

- url: /img
  static_dir: static/img

- url: /docs
  static_dir: static/docs

- url: /.*
  static_files: static/index.html
  upload: static/index.html
